name: Deploy to Alibaba Cloud ECS

on:
  # 监控的 github 分支
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: davidzhu/django-test2  # 镜像名，阿里云的镜像仓库命名规则
  IMAGE_TAG: v0.1.10                 # 镜像的版本号，   
  REGION: cn-shanghai                # 阿里云镜像地址   
  ACCESS_KEY_ID: ${{ secrets.ALIYUN_ACCESS_KEY }}      # 登陆阿里云ecs 服务器 id ，可以是 root,放在 secrets中
  ACCESS_KEY_SECRET: ${{ secrets.ALIYUN_SECRET_KEY }}   # 登陆阿里云 ecs 服务器 私钥，放在 secrets 中
  ECS_CLUSTER_ID:  ${{ secrets.ALIYUN_HOST }}                       # 阿里云服务器地址
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
    # Checkout the repository
    - name: Checkout
      uses: actions/checkout@v2
      
    # Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        
    # 登陆 阿里云镜像仓库地址
    - name: Configure Docker
      uses: docker/login-action@v1
      with:
        registry: registry.${{ env.REGION }}.aliyuncs.com
        username: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
        password: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}

    #- name: Install Python dependencies
    #  run: |
    #    sudo apt-get update
    #    sudo apt-get -y install python3-pip
    #    pip3 install -r requirements.txt
    
    # 更具代码仓库的Dockerfile创建镜像并且 推送到服务器 
    - name: Build Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: registry.${{ env.REGION }}.aliyuncs.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
        build-args: |
            DJANGO_SECRET_KEY=${{ env.DJANGO_SECRET_KEY }}
      env:
        DOCKER_USERNAME: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
      
    
    # 远程 ssh 连接 阿里云ecs 服务器并且部署
    - name: ssh deploy
      # You may pin to the exact commit or the version.
      # uses: easingthemes/ssh-deploy@3884c8554ff45c0fd37d3f12a76288d06ce7a2ff
      uses: easingthemes/ssh-deploy@v4.1.8
      with:
        # Private key part of an SSH key pair,ssh 连接密钥
        SSH_PRIVATE_KEY: ${{ env.ACCESS_KEY_SECRET }}
        # Remote host
        REMOTE_HOST: ${{ env.ECS_CLUSTER_ID }}
        # Remote user
        REMOTE_USER: ${{ env.ACCESS_KEY_ID }}
        # Source directory, path relative to `$GITHUB_WORKSPACE` root, eg: `dist/`
        # SOURCE: "./dist" # optional, default is 
        
        # Target directory,把当前的项目代码目标拷贝到Target目录 /opt/djangotest1
        TARGET:  "/opt/djangotest2"
      
       
       
        #  登陆 阿里云镜像仓库,
        # 拉取刚刚推送的镜像，
        # 把 /opt/djangotest2/docker-compose.yaml 文件中的 image 镜像修改成刚刚拉取的镜像
        # 把 /opt/djangotest2/docker-compose.yaml 文件中的 image 镜像修改成刚刚拉取的镜像
        # 把之前的使用的镜像服务停掉删除
        # 删除标签为 <none> 的镜像
        # 删除原来的挂载的 static的文件夹，重新建立 rm -f /opt/djangotest2/djangostatic/* mkdir /opt/djangotest2/djangostatic
        # 使用 /opt/djangotest2/docker-compose.yaml 启动新的镜像服务
        # 使用 /opt/djangotest2/docker-compose.yaml 启动新的镜像服务
        SCRIPT_AFTER: |
          

          docker login --username=${{ secrets.ALIYUN_CONTAINER_REGISTRY_USERNAME }} registry.${{ env.REGION }}.aliyuncs.com --password=${{ secrets.ALIYUN_CONTAINER_REGISTRY_PASSWORD }}
          
          docker pull registry.${{ env.REGION }}.aliyuncs.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          
          sed -i "s|image:.*|image: registry.${{ env.REGION }}.aliyuncs.com/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}|" /opt/djangotest2/docker-compose.yml
          
          docker-compose -f /opt/djangotest2/docker-compose.yml down
          
          
          docker image prune -f --filter "dangling=true"

          docker-compose -f /opt/djangotest2/docker-compose.yml up -d
